version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password

  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ../monitoring/prometheus-quarkus.yml:/etc/prometheus/prometheus.yml

  database:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_DB: review
      POSTGRES_USER: review-app
      POSTGRES_PASSWORD: review-app
    ports:
    - 5432:5432

  activemq:
    image: vromero/activemq-artemis:latest-alpine
    restart: always
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    ports:
    - 8161:8161
    - 61616:61616

  app:
    build:
      context: quarkus-app
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: on-failure
    environment:
      quarkus.datasource.jdbc.url: "jdbc:postgresql://database:5432/review"
      quarkus.datasource.username: review-app
      quarkus.datasource.password: review-app
      quarkus.artemis.url: "tcp://activemq:61616"
      quarkus.artemis.username: admin
      quarkus.artemis.password: admin
    ports:
    - 8080:8080
    depends_on:
      - database
      - activemq