sudo: required
language: java
services:
  - docker

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.sonar/cache

env:
  global:
    - SHA=$(git rev-parse --short HEAD)
    - DATETIME=$(date +"%y%m%d%H%M%S")
    - TAG=$DATETIME-$SHA

addons:
  sonarcloud:
    organization: "brunokarpo"
    token:
      secure: "uPRHpX9k7e0h5UR56RQmqRQaKwPlmC3pFOVKc5aZPEw1jwo4wqUtMpPLOfCQZiZ9XOOCqGEAlrDYWyJnsHqauLx3jgxrJmo+3Ono0k1uobQUI/jPSS5JYEdAb1cVbgfj/tzu+nJK8gyeR7V2tZknYoYc578h2rm5dsbIQCwnHRAtOTHv2fJCqiX/k4C1EbtvcVGSCg9bfLFi2pmGFP4lpe2uwB8uqBCJA2xVxJk7N/xx/9dEjxs88S75ye7EmjstqtgQmJfUlQmKidMZG2jRfC6dQFN3fZzcUhPHHcuXzt5NRxa8cj3MF26Ifdgcvi7hHo8EzfacVTZiMXNS6Tvtw5AqPE7mLb0sdA5zNSpG4Db/hrxgt0NL3XDMYPO29v4YPjxrQTifouDtDpW4EA486UPYhzw86eyvWrAeNeaXZPihf0eg9Wd0393+IifZ9pYSFLRLzhDhg/HMWSouNGgNxv6IEyRpOCuYA+h/fB7S/dakRbWiDUUtN3BRjNwn+W1WF1danmEAGFacEiphgd9QXLVz8cvXcJMheKM1Z4FdBYhi8/FoEtX9waEcxesC7+FXcid03pwUiExSF10G71HEvnmDsPstb47HHSd1MEBsd4MWavJvDNc8OlSbhQBRLEerpVSllNy0IpaOBjF1lTwQm8g8m8tUoma/bnk4RCU80qo="

script:
  - ./mvnw clean install -Pcoverage sonar:sonar -Dsonar.projectKey=brunokarpo_review-training

after_success:
  - docker image build -f app/src/main/docker/Dockerfile.jvm -t brunokarpo/review-app:latest -t brunokarpo/review-app:$TAG app/.

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master