sudo: required
language: java
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse --short HEAD)
    - DATETIME=$(date +"%y%m%d%H%M%S")
    - TAG=$DATETIME-$SHA

addons:
  sonarcloud:
    organization: "brunokarpo"
    token:
      secure: "$SONAR_TOKEN"

script:
  - ./mvnw clean install

after_success:
  - docker image build -f app/src/main/docker/Dockerfile.jvm -t brunokarpo/review-app:latest -t brunokarpo/review-app:$TAG app/.

deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: script
  script: deploy.sh