server:
  servlet:
    context-path: /review
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: review-app
    password: review-app
management:
  server:
    port: 8081
    servlet:
      context-path: "/"
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "health,info,metrics"
