apiVersion: v1
kind: ConfigMap
metadata:
  name: review-application-config-map
  namespace: review-application
data:
  SERVER_PORT: "8080"
  SERVER_CONTEXT: /review
  DATABASE_URL: "jdbc:postgresql://postgres-cluster-ip.review-application:5432/review"
  DATABASE_USERNAME: "review-app"