apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
  namespace: review-application
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi