apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip
  namespace: review-application
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432