# Configuration file
quarkus:
  resteasy:
    path: /review
  datasource:
    db-kind: postgresql
    username: review-app
    password: review-app
    jdbc:
      url: jdbc:postgresql://localhost:5432/review
      driver: org.postgresql.Driver
  flyway:
    migrate-at-start: true
  artemis:
    url: tcp://localhost:61616
    username: admin
    password: admin