version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password

  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  database:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_DB: review
      POSTGRES_USER: review-app
      POSTGRES_PASSWORD: review-app
    ports:
    - 5432:5432

  activemq:
    image: webcenter/activemq:latest
    restart: always
    environment:
      ACTIVEMQ_CONFIG_NAME: amqp-srv1
      ACTIVEMQ_CONFIG_DEFAULTACCOUNT: "false"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_CONFIG_MINMEMORY: 256
      ACTIVEMQ_CONFIG_MAXMEMORY: 1024
    ports:
    - 8161:8161
    - 61616:61616
    - 61613:61613

  app:
    build:
      context: app
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: on-failure
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/review"
      DATABASE_USERNAME: review-app
      DATABASE_PASSWORD: review-app
      ACTIVEMQ_URL: "tcp://activemq:61616"
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
    ports:
    - 8080:8080
    - 8081:8081
    depends_on:
      - database
      - activemq