micronaut:
  application:
    name: micronaut-app

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/review
    username: review-app
    password: review-app
    driver-class-name: org.postgresql.Driver
flyway:
  datasources:
    default:
      enabled: true